material_kg = float(input("Ingrese los kilogramos de material: "))
costo_por_kg = float(input("Ingrese el costo por kilogramo: "))
print("Costo total del material")
print(material_kg, "*", costo_por_kg, material_kg * costo_por_kg)
print("Diferencia contra presupuesto")
presupuesto = float(input("Ingrese el presupuesto asignado: "))
print(presupuesto, "-", material_kg * costo_por_kg, presupuesto - material_kg * costo_por_kg)
print("Unidades producidas estimadas")
peso_pieza = float(input("Ingrese el peso por pieza (kg): "))
print(material_kg, "/", peso_pieza, material_kg // peso_pieza)
print("Material sobrante")
print(material_kg, "%", peso_pieza, material_kg % peso_pieza)
print("Eficiencia al cuadrado del lote")
print(material_kg, "**", 2, material_kg ** 2)
