numero1=float(input("Ingrese el primer número: "))
numero2=float(input("Ingrese el segundo número: "))
print("Suma")
print(numero1,"+",numero2,numero1+numero2)
print("Resta")
print(numero1,"-",numero2,numero1-numero2)
print("Multiplicación")
print(numero1,"*",numero2,numero1*numero2)
print("División")
print(numero1,"/",numero2,numero1/numero2)
print("Módulo")
print(numero1,"%",numero2,numero1%numero2)
print("Exponentes")
print(numero1,"*",numero2,numero1*numero2)